// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: config.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace KinesisProducerNet.Protobuf
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AdditionalDimension
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public string Value { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"granularity", IsRequired = true)]
        public string Granularity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Configuration
    {
        [global::ProtoBuf.ProtoMember(128, Name = @"additional_metric_dims")]
        public global::System.Collections.Generic.List<AdditionalDimension> AdditionalMetricDims { get; } = new global::System.Collections.Generic.List<AdditionalDimension>();

        [global::ProtoBuf.ProtoMember(1, Name = @"aggregation_enabled")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool AggregationEnabled
        {
            get { return __pbn__AggregationEnabled ?? true; }
            set { __pbn__AggregationEnabled = value; }
        }
        public bool ShouldSerializeAggregationEnabled() => __pbn__AggregationEnabled != null;
        public void ResetAggregationEnabled() => __pbn__AggregationEnabled = null;
        private bool? __pbn__AggregationEnabled;

        [global::ProtoBuf.ProtoMember(2, Name = @"aggregation_max_count")]
        [global::System.ComponentModel.DefaultValue(4294967295)]
        public ulong AggregationMaxCount
        {
            get { return __pbn__AggregationMaxCount ?? 4294967295; }
            set { __pbn__AggregationMaxCount = value; }
        }
        public bool ShouldSerializeAggregationMaxCount() => __pbn__AggregationMaxCount != null;
        public void ResetAggregationMaxCount() => __pbn__AggregationMaxCount = null;
        private ulong? __pbn__AggregationMaxCount;

        [global::ProtoBuf.ProtoMember(3, Name = @"aggregation_max_size")]
        [global::System.ComponentModel.DefaultValue(51200)]
        public ulong AggregationMaxSize
        {
            get { return __pbn__AggregationMaxSize ?? 51200; }
            set { __pbn__AggregationMaxSize = value; }
        }
        public bool ShouldSerializeAggregationMaxSize() => __pbn__AggregationMaxSize != null;
        public void ResetAggregationMaxSize() => __pbn__AggregationMaxSize = null;
        private ulong? __pbn__AggregationMaxSize;

        [global::ProtoBuf.ProtoMember(4, Name = @"cloudwatch_endpoint")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CloudwatchEndpoint
        {
            get { return __pbn__CloudwatchEndpoint ?? ""; }
            set { __pbn__CloudwatchEndpoint = value; }
        }
        public bool ShouldSerializeCloudwatchEndpoint() => __pbn__CloudwatchEndpoint != null;
        public void ResetCloudwatchEndpoint() => __pbn__CloudwatchEndpoint = null;
        private string __pbn__CloudwatchEndpoint;

        [global::ProtoBuf.ProtoMember(5, Name = @"cloudwatch_port")]
        [global::System.ComponentModel.DefaultValue(443)]
        public ulong CloudwatchPort
        {
            get { return __pbn__CloudwatchPort ?? 443; }
            set { __pbn__CloudwatchPort = value; }
        }
        public bool ShouldSerializeCloudwatchPort() => __pbn__CloudwatchPort != null;
        public void ResetCloudwatchPort() => __pbn__CloudwatchPort = null;
        private ulong? __pbn__CloudwatchPort;

        [global::ProtoBuf.ProtoMember(6, Name = @"collection_max_count")]
        [global::System.ComponentModel.DefaultValue(500)]
        public ulong CollectionMaxCount
        {
            get { return __pbn__CollectionMaxCount ?? 500; }
            set { __pbn__CollectionMaxCount = value; }
        }
        public bool ShouldSerializeCollectionMaxCount() => __pbn__CollectionMaxCount != null;
        public void ResetCollectionMaxCount() => __pbn__CollectionMaxCount = null;
        private ulong? __pbn__CollectionMaxCount;

        [global::ProtoBuf.ProtoMember(7, Name = @"collection_max_size")]
        [global::System.ComponentModel.DefaultValue(5242880)]
        public ulong CollectionMaxSize
        {
            get { return __pbn__CollectionMaxSize ?? 5242880; }
            set { __pbn__CollectionMaxSize = value; }
        }
        public bool ShouldSerializeCollectionMaxSize() => __pbn__CollectionMaxSize != null;
        public void ResetCollectionMaxSize() => __pbn__CollectionMaxSize = null;
        private ulong? __pbn__CollectionMaxSize;

        [global::ProtoBuf.ProtoMember(8, Name = @"connect_timeout")]
        [global::System.ComponentModel.DefaultValue(6000)]
        public ulong ConnectTimeout
        {
            get { return __pbn__ConnectTimeout ?? 6000; }
            set { __pbn__ConnectTimeout = value; }
        }
        public bool ShouldSerializeConnectTimeout() => __pbn__ConnectTimeout != null;
        public void ResetConnectTimeout() => __pbn__ConnectTimeout = null;
        private ulong? __pbn__ConnectTimeout;

        [global::ProtoBuf.ProtoMember(9, Name = @"enable_core_dumps")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool EnableCoreDumps
        {
            get { return __pbn__EnableCoreDumps ?? false; }
            set { __pbn__EnableCoreDumps = value; }
        }
        public bool ShouldSerializeEnableCoreDumps() => __pbn__EnableCoreDumps != null;
        public void ResetEnableCoreDumps() => __pbn__EnableCoreDumps = null;
        private bool? __pbn__EnableCoreDumps;

        [global::ProtoBuf.ProtoMember(10, Name = @"fail_if_throttled")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool FailIfThrottled
        {
            get { return __pbn__FailIfThrottled ?? false; }
            set { __pbn__FailIfThrottled = value; }
        }
        public bool ShouldSerializeFailIfThrottled() => __pbn__FailIfThrottled != null;
        public void ResetFailIfThrottled() => __pbn__FailIfThrottled = null;
        private bool? __pbn__FailIfThrottled;

        [global::ProtoBuf.ProtoMember(11, Name = @"kinesis_endpoint")]
        [global::System.ComponentModel.DefaultValue("")]
        public string KinesisEndpoint
        {
            get { return __pbn__KinesisEndpoint ?? ""; }
            set { __pbn__KinesisEndpoint = value; }
        }
        public bool ShouldSerializeKinesisEndpoint() => __pbn__KinesisEndpoint != null;
        public void ResetKinesisEndpoint() => __pbn__KinesisEndpoint = null;
        private string __pbn__KinesisEndpoint;

        [global::ProtoBuf.ProtoMember(12, Name = @"kinesis_port")]
        [global::System.ComponentModel.DefaultValue(443)]
        public ulong KinesisPort
        {
            get { return __pbn__KinesisPort ?? 443; }
            set { __pbn__KinesisPort = value; }
        }
        public bool ShouldSerializeKinesisPort() => __pbn__KinesisPort != null;
        public void ResetKinesisPort() => __pbn__KinesisPort = null;
        private ulong? __pbn__KinesisPort;

        [global::ProtoBuf.ProtoMember(13, Name = @"log_level")]
        [global::System.ComponentModel.DefaultValue(@"info")]
        public string LogLevel
        {
            get { return __pbn__LogLevel ?? @"info"; }
            set { __pbn__LogLevel = value; }
        }
        public bool ShouldSerializeLogLevel() => __pbn__LogLevel != null;
        public void ResetLogLevel() => __pbn__LogLevel = null;
        private string __pbn__LogLevel;

        [global::ProtoBuf.ProtoMember(14, Name = @"max_connections")]
        [global::System.ComponentModel.DefaultValue(24)]
        public ulong MaxConnections
        {
            get { return __pbn__MaxConnections ?? 24; }
            set { __pbn__MaxConnections = value; }
        }
        public bool ShouldSerializeMaxConnections() => __pbn__MaxConnections != null;
        public void ResetMaxConnections() => __pbn__MaxConnections = null;
        private ulong? __pbn__MaxConnections;

        [global::ProtoBuf.ProtoMember(15, Name = @"metrics_granularity")]
        [global::System.ComponentModel.DefaultValue(@"shard")]
        public string MetricsGranularity
        {
            get { return __pbn__MetricsGranularity ?? @"shard"; }
            set { __pbn__MetricsGranularity = value; }
        }
        public bool ShouldSerializeMetricsGranularity() => __pbn__MetricsGranularity != null;
        public void ResetMetricsGranularity() => __pbn__MetricsGranularity = null;
        private string __pbn__MetricsGranularity;

        [global::ProtoBuf.ProtoMember(16, Name = @"metrics_level")]
        [global::System.ComponentModel.DefaultValue(@"detailed")]
        public string MetricsLevel
        {
            get { return __pbn__MetricsLevel ?? @"detailed"; }
            set { __pbn__MetricsLevel = value; }
        }
        public bool ShouldSerializeMetricsLevel() => __pbn__MetricsLevel != null;
        public void ResetMetricsLevel() => __pbn__MetricsLevel = null;
        private string __pbn__MetricsLevel;

        [global::ProtoBuf.ProtoMember(17, Name = @"metrics_namespace")]
        [global::System.ComponentModel.DefaultValue(@"KinesisProducerLibrary")]
        public string MetricsNamespace
        {
            get { return __pbn__MetricsNamespace ?? @"KinesisProducerLibrary"; }
            set { __pbn__MetricsNamespace = value; }
        }
        public bool ShouldSerializeMetricsNamespace() => __pbn__MetricsNamespace != null;
        public void ResetMetricsNamespace() => __pbn__MetricsNamespace = null;
        private string __pbn__MetricsNamespace;

        [global::ProtoBuf.ProtoMember(18, Name = @"metrics_upload_delay")]
        [global::System.ComponentModel.DefaultValue(60000)]
        public ulong MetricsUploadDelay
        {
            get { return __pbn__MetricsUploadDelay ?? 60000; }
            set { __pbn__MetricsUploadDelay = value; }
        }
        public bool ShouldSerializeMetricsUploadDelay() => __pbn__MetricsUploadDelay != null;
        public void ResetMetricsUploadDelay() => __pbn__MetricsUploadDelay = null;
        private ulong? __pbn__MetricsUploadDelay;

        [global::ProtoBuf.ProtoMember(19, Name = @"min_connections")]
        [global::System.ComponentModel.DefaultValue(1)]
        public ulong MinConnections
        {
            get { return __pbn__MinConnections ?? 1; }
            set { __pbn__MinConnections = value; }
        }
        public bool ShouldSerializeMinConnections() => __pbn__MinConnections != null;
        public void ResetMinConnections() => __pbn__MinConnections = null;
        private ulong? __pbn__MinConnections;

        [global::ProtoBuf.ProtoMember(20, Name = @"rate_limit")]
        [global::System.ComponentModel.DefaultValue(150)]
        public ulong RateLimit
        {
            get { return __pbn__RateLimit ?? 150; }
            set { __pbn__RateLimit = value; }
        }
        public bool ShouldSerializeRateLimit() => __pbn__RateLimit != null;
        public void ResetRateLimit() => __pbn__RateLimit = null;
        private ulong? __pbn__RateLimit;

        [global::ProtoBuf.ProtoMember(21, Name = @"record_max_buffered_time")]
        [global::System.ComponentModel.DefaultValue(100)]
        public ulong RecordMaxBufferedTime
        {
            get { return __pbn__RecordMaxBufferedTime ?? 100; }
            set { __pbn__RecordMaxBufferedTime = value; }
        }
        public bool ShouldSerializeRecordMaxBufferedTime() => __pbn__RecordMaxBufferedTime != null;
        public void ResetRecordMaxBufferedTime() => __pbn__RecordMaxBufferedTime = null;
        private ulong? __pbn__RecordMaxBufferedTime;

        [global::ProtoBuf.ProtoMember(22, Name = @"record_ttl")]
        [global::System.ComponentModel.DefaultValue(30000)]
        public ulong RecordTtl
        {
            get { return __pbn__RecordTtl ?? 30000; }
            set { __pbn__RecordTtl = value; }
        }
        public bool ShouldSerializeRecordTtl() => __pbn__RecordTtl != null;
        public void ResetRecordTtl() => __pbn__RecordTtl = null;
        private ulong? __pbn__RecordTtl;

        [global::ProtoBuf.ProtoMember(23, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region
        {
            get { return __pbn__Region ?? ""; }
            set { __pbn__Region = value; }
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private string __pbn__Region;

        [global::ProtoBuf.ProtoMember(24, Name = @"request_timeout")]
        [global::System.ComponentModel.DefaultValue(6000)]
        public ulong RequestTimeout
        {
            get { return __pbn__RequestTimeout ?? 6000; }
            set { __pbn__RequestTimeout = value; }
        }
        public bool ShouldSerializeRequestTimeout() => __pbn__RequestTimeout != null;
        public void ResetRequestTimeout() => __pbn__RequestTimeout = null;
        private ulong? __pbn__RequestTimeout;

        [global::ProtoBuf.ProtoMember(25, Name = @"verify_certificate")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool VerifyCertificate
        {
            get { return __pbn__VerifyCertificate ?? true; }
            set { __pbn__VerifyCertificate = value; }
        }
        public bool ShouldSerializeVerifyCertificate() => __pbn__VerifyCertificate != null;
        public void ResetVerifyCertificate() => __pbn__VerifyCertificate = null;
        private bool? __pbn__VerifyCertificate;

        [global::ProtoBuf.ProtoMember(26)]
        [global::System.ComponentModel.DefaultValue(ThreadConfig.PerRequest)]
        public ThreadConfig thread_config
        {
            get { return __pbn__thread_config ?? ThreadConfig.PerRequest; }
            set { __pbn__thread_config = value; }
        }
        public bool ShouldSerializethread_config() => __pbn__thread_config != null;
        public void Resetthread_config() => __pbn__thread_config = null;
        private ThreadConfig? __pbn__thread_config;

        [global::ProtoBuf.ProtoMember(27, Name = @"thread_pool_size")]
        [global::System.ComponentModel.DefaultValue(64)]
        public uint ThreadPoolSize
        {
            get { return __pbn__ThreadPoolSize ?? 64; }
            set { __pbn__ThreadPoolSize = value; }
        }
        public bool ShouldSerializeThreadPoolSize() => __pbn__ThreadPoolSize != null;
        public void ResetThreadPoolSize() => __pbn__ThreadPoolSize = null;
        private uint? __pbn__ThreadPoolSize;

        [global::ProtoBuf.ProtoContract()]
        public enum ThreadConfig
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PER_REQUEST")]
            PerRequest = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"POOLED")]
            Pooled = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021