// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace KinesisProducerNet.Protobuf
{
    [global::ProtoBuf.ProtoContract()]
    public partial class Tag
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Record
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"partition_key_index", IsRequired = true)]
        public ulong PartitionKeyIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"explicit_hash_key_index")]
        public ulong ExplicitHashKeyIndex
        {
            get { return __pbn__ExplicitHashKeyIndex.GetValueOrDefault(); }
            set { __pbn__ExplicitHashKeyIndex = value; }
        }
        public bool ShouldSerializeExplicitHashKeyIndex() => __pbn__ExplicitHashKeyIndex != null;
        public void ResetExplicitHashKeyIndex() => __pbn__ExplicitHashKeyIndex = null;
        private ulong? __pbn__ExplicitHashKeyIndex;

        [global::ProtoBuf.ProtoMember(3, Name = @"data", IsRequired = true)]
        public byte[] Data { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"tags")]
        public global::System.Collections.Generic.List<Tag> Tags { get; } = new global::System.Collections.Generic.List<Tag>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AggregatedRecord
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"partition_key_table")]
        public global::System.Collections.Generic.List<string> PartitionKeyTables { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"explicit_hash_key_table")]
        public global::System.Collections.Generic.List<string> ExplicitHashKeyTables { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"records")]
        public global::System.Collections.Generic.List<Record> Records { get; } = new global::System.Collections.Generic.List<Record>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Message
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"source_id")]
        public ulong SourceId
        {
            get { return __pbn__SourceId.GetValueOrDefault(); }
            set { __pbn__SourceId = value; }
        }
        public bool ShouldSerializeSourceId() => __pbn__SourceId != null;
        public void ResetSourceId() => __pbn__SourceId = null;
        private ulong? __pbn__SourceId;

        [global::ProtoBuf.ProtoMember(3, Name = @"put_record")]
        public PutRecord PutRecord
        {
            get { return __pbn__actual_message.Is(3) ? ((PutRecord)__pbn__actual_message.Object) : default(PutRecord); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializePutRecord() => __pbn__actual_message.Is(3);
        public void ResetPutRecord() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__actual_message;

        [global::ProtoBuf.ProtoMember(4, Name = @"flush")]
        public Flush Flush
        {
            get { return __pbn__actual_message.Is(4) ? ((Flush)__pbn__actual_message.Object) : default(Flush); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeFlush() => __pbn__actual_message.Is(4);
        public void ResetFlush() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"put_record_result")]
        public PutRecordResult PutRecordResult
        {
            get { return __pbn__actual_message.Is(5) ? ((PutRecordResult)__pbn__actual_message.Object) : default(PutRecordResult); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializePutRecordResult() => __pbn__actual_message.Is(5);
        public void ResetPutRecordResult() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"configuration")]
        public Configuration Configuration
        {
            get { return __pbn__actual_message.Is(6) ? ((Configuration)__pbn__actual_message.Object) : default(Configuration); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeConfiguration() => __pbn__actual_message.Is(6);
        public void ResetConfiguration() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"metrics_request")]
        public MetricsRequest MetricsRequest
        {
            get { return __pbn__actual_message.Is(7) ? ((MetricsRequest)__pbn__actual_message.Object) : default(MetricsRequest); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializeMetricsRequest() => __pbn__actual_message.Is(7);
        public void ResetMetricsRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"metrics_response")]
        public MetricsResponse MetricsResponse
        {
            get { return __pbn__actual_message.Is(8) ? ((MetricsResponse)__pbn__actual_message.Object) : default(MetricsResponse); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializeMetricsResponse() => __pbn__actual_message.Is(8);
        public void ResetMetricsResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 8);

        [global::ProtoBuf.ProtoMember(9, Name = @"set_credentials")]
        public SetCredentials SetCredentials
        {
            get { return __pbn__actual_message.Is(9) ? ((SetCredentials)__pbn__actual_message.Object) : default(SetCredentials); }
            set { __pbn__actual_message = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializeSetCredentials() => __pbn__actual_message.Is(9);
        public void ResetSetCredentials() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__actual_message, 9);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutRecord
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"stream_name", IsRequired = true)]
        public string StreamName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"partition_key", IsRequired = true)]
        public string PartitionKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"explicit_hash_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExplicitHashKey
        {
            get { return __pbn__ExplicitHashKey ?? ""; }
            set { __pbn__ExplicitHashKey = value; }
        }
        public bool ShouldSerializeExplicitHashKey() => __pbn__ExplicitHashKey != null;
        public void ResetExplicitHashKey() => __pbn__ExplicitHashKey = null;
        private string __pbn__ExplicitHashKey;

        [global::ProtoBuf.ProtoMember(4, Name = @"data", IsRequired = true)]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Flush
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"stream_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StreamName
        {
            get { return __pbn__StreamName ?? ""; }
            set { __pbn__StreamName = value; }
        }
        public bool ShouldSerializeStreamName() => __pbn__StreamName != null;
        public void ResetStreamName() => __pbn__StreamName = null;
        private string __pbn__StreamName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Attempt
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"delay", IsRequired = true)]
        public uint Delay { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"duration", IsRequired = true)]
        public uint Duration { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"success", IsRequired = true)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"error_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorCode
        {
            get { return __pbn__ErrorCode ?? ""; }
            set { __pbn__ErrorCode = value; }
        }
        public bool ShouldSerializeErrorCode() => __pbn__ErrorCode != null;
        public void ResetErrorCode() => __pbn__ErrorCode = null;
        private string __pbn__ErrorCode;

        [global::ProtoBuf.ProtoMember(5, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage
        {
            get { return __pbn__ErrorMessage ?? ""; }
            set { __pbn__ErrorMessage = value; }
        }
        public bool ShouldSerializeErrorMessage() => __pbn__ErrorMessage != null;
        public void ResetErrorMessage() => __pbn__ErrorMessage = null;
        private string __pbn__ErrorMessage;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutRecordResult
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"attempts")]
        public global::System.Collections.Generic.List<Attempt> Attempts { get; } = new global::System.Collections.Generic.List<Attempt>();

        [global::ProtoBuf.ProtoMember(2, Name = @"success", IsRequired = true)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shard_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ShardId
        {
            get { return __pbn__ShardId ?? ""; }
            set { __pbn__ShardId = value; }
        }
        public bool ShouldSerializeShardId() => __pbn__ShardId != null;
        public void ResetShardId() => __pbn__ShardId = null;
        private string __pbn__ShardId;

        [global::ProtoBuf.ProtoMember(4, Name = @"sequence_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SequenceNumber
        {
            get { return __pbn__SequenceNumber ?? ""; }
            set { __pbn__SequenceNumber = value; }
        }
        public bool ShouldSerializeSequenceNumber() => __pbn__SequenceNumber != null;
        public void ResetSequenceNumber() => __pbn__SequenceNumber = null;
        private string __pbn__SequenceNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Credentials
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"akid", IsRequired = true)]
        public string Akid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"secret_key", IsRequired = true)]
        public string SecretKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get { return __pbn__Token ?? ""; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetCredentials
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"for_metrics")]
        public bool ForMetrics
        {
            get { return __pbn__ForMetrics.GetValueOrDefault(); }
            set { __pbn__ForMetrics = value; }
        }
        public bool ShouldSerializeForMetrics() => __pbn__ForMetrics != null;
        public void ResetForMetrics() => __pbn__ForMetrics = null;
        private bool? __pbn__ForMetrics;

        [global::ProtoBuf.ProtoMember(2, Name = @"credentials", IsRequired = true)]
        public Credentials Credentials { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Dimension
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public string Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Stats
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"count", IsRequired = true)]
        public double Count { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sum", IsRequired = true)]
        public double Sum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mean", IsRequired = true)]
        public double Mean { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"min", IsRequired = true)]
        public double Min { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max", IsRequired = true)]
        public double Max { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Metric
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dimensions")]
        public global::System.Collections.Generic.List<Dimension> Dimensions { get; } = new global::System.Collections.Generic.List<Dimension>();

        [global::ProtoBuf.ProtoMember(3, Name = @"stats", IsRequired = true)]
        public Stats Stats { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"seconds", IsRequired = true)]
        public ulong Seconds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MetricsRequest
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"seconds")]
        public ulong Seconds
        {
            get { return __pbn__Seconds.GetValueOrDefault(); }
            set { __pbn__Seconds = value; }
        }
        public bool ShouldSerializeSeconds() => __pbn__Seconds != null;
        public void ResetSeconds() => __pbn__Seconds = null;
        private ulong? __pbn__Seconds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MetricsResponse
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"metrics")]
        public global::System.Collections.Generic.List<Metric> Metrics { get; } = new global::System.Collections.Generic.List<Metric>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
